/*
# Requirements

*/

export type Compiler {

}

export type Publisher {

}

// These are the main actions that a user can do after selecting their preferred shipper.
export type ShipperActions {
    // SHIPPER_LEARN_OPERATING_SYSTEM: 'SHIPPER_LEARN_OPERATING_SYSTEM',
    // SHIPPER_SETUPASSIST_OPERATING_SYSTEM: 'SHIPPER_LEARN_OPERATING_SYSTEM',

    // SHIPPER_LEARN_TERMINAL: 'SHIPPER_LEARN_TERMINAL',
    // SHIPPER_SETUPASSIST_TERMINAL: 'SHIPPER_SETUPASSIST_TERMINAL',

    // SHIPPER_LEARN_GIT: 'SHIPPER_LEARN_GIT',
    // SHIPPER_SETUPASSIST_GIT: 'SHIPPER_SETUP_GIT',

    // SHIPPER_LEARN_GIT_STAGES
    // SHIPPER_SETUPASSIST_GIT_STAGES
    // SHIPPER_CREATE_GIT_STAGES
    // SHIPPER_UPDATE_GIT_STAGE:
    // SHIPPER_GIT_SYNC_STAGE: [],
    // SHIPPER_GIT_FIXMERGECONFLICT:
    // SHIPPER_GIT_RESET_STAGE:

    // SHIPPER_LEARN_TARGETS: 'SHIPPER_LEARN_TARGETS',
    // SHIPPER_SETUPASSIST_TARGETS: 'SHIPPER_SETUPASSIST_TARGETS',
    // SHIPPER_UPDATE_TARGETS: 'SHIPPER_UPDATE_TARGETS',

    // SHIPPER_LEARN_PUBLISHER: 'SHIPPER_LEARN_PUBLISHER',
    // SHIPPER_SETUPASSIST_PUBSLIHER: 'SHIPPER_SETUPASSIST_PUBLISHER',
    // SHIPPER_UPDATE_PUBLISHER: 'SHIPPER_UPDATE_PUBLISHER'

    // SHIPPER_LEARN_CI: 'SHIPPER_LEARN_CI',
    // SHIPPER_SETUPASSIST_CI: 'SHIPPER_SETUPASSIST_CI',
    // SHIPPER_UPDATE_CI: 'SHIPPER_UPDATE_CI',
    // SHIPPER_PUBLISH_CI: 'SHIPPER_PUBLISH_CI',

    // SHIPPER_LEARN_LANGUAGES: 'SHIPPER_LEARN_LANGUAGES',
    // SHIPPER_SETUPASSIST_LANGUAGES: 'SHIPPER_SETUPASSIST_LANGUAGES',
    // SHIPPER_UPDATE_LANGUAGES: 'SHIPPER_UPDATE_LANGUAGES',

    // SHIPPER_LEARN_DESIGN_PATTERNS: 'SHIPPER_LEARN_EDITOR',
    // SHIPPER_SETUPASSIST_DESIGN_PATTERNS: 'SHIPPER_LEARN_EDITOR',
    // SHIPPER_UPDATE_DESIGN_PATTERNS: 'SHIPPER_LEARN_EDITOR',

    // SHIPPER_LEARN_EDITOR: 'SHIPPER_LEARN_EDITOR',
    // SHIPPER_SETUPASSIST_EDITOR: 'SHIPPER_SETUPASSIST_EDITOR',

    // SHIPPER_LEARN_VALIDATOR: 'SHIPPER_LEARN_VALIDATOR',
    // SHIPPER_SETUPASSIST_VALIDATOR: 'SHIPPER_SETUP_VALIDATOR',
    // SHIPPER_UPDATE_VALIDATORS: 'SHIPPER_UPDATE_VALIDATORS',

    // SHIPPER_LEARN_TESTS: 'SHIPPER_LEARN_TESTS',
    // SHIPPER_SETUPASSIST_TESTS: 'SHIPPER_SETUPASSIST_TESTS',
    // SHIPPER_UPDATE_TESTS: 'SHIPPER_UPDATE_TESTS',
}

export type Shipper {
  process: 'yarn-gitflow',
  availableProcesses: [],
  updater: 'semantic-release',
  availableUpdater: [],
  validator: any,
  test: any,
  compiler: any,
  docs: any,
}

export type Communications {
  brand: string,
  goal: string,
  description: string,
}